Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ase import Atoms as AseAtoms
from ase.data.colors import jmol_colors
from ase.visualize.plot import plot_atoms

import matplotlib.pyplot as plt
%matplotlib inline

fig, ax = plt.subplots(figsize=(3,3))
ase_atoms = AseAtoms(positions=positions, numbers=numbers, cell=cell)
plot_atoms(ase_atoms, ax, radii=0.3, rotation=("10x,20y,0z"), show_unit_cell=2)
ax.axis("off");

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 9[0m
[1;32m      6[0m get_ipython()[38;5;241m.[39mrun_line_magic([38;5;124m'[39m[38;5;124mmatplotlib[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124minline[39m[38;5;124m'[39m)
[1;32m      8[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots(figsize[38;5;241m=[39m([38;5;241m3[39m,[38;5;241m3[39m))
[0;32m----> 9[0m ase_atoms [38;5;241m=[39m AseAtoms(positions[38;5;241m=[39m[43mpositions[49m, numbers[38;5;241m=[39mnumbers, cell[38;5;241m=[39mcell)
[1;32m     10[0m plot_atoms(ase_atoms, ax, radii[38;5;241m=[39m[38;5;241m0.3[39m, rotation[38;5;241m=[39m([38;5;124m"[39m[38;5;124m10x,20y,0z[39m[38;5;124m"[39m), show_unit_cell[38;5;241m=[39m[38;5;241m2[39m)
[1;32m     11[0m ax[38;5;241m.[39maxis([38;5;124m"[39m[38;5;124moff[39m[38;5;124m"[39m);

[0;31mNameError[0m: name 'positions' is not defined

